Main:
<Main>:

    orientation: 'vertical'

    Label:
        text: "Welcome to Steambot"
        font_name: 'OLDENGL.TTF'
        font_size: 54
        color: (0, 0, 0, 1)
        background_color: (.1, .15, .25, 1)
        size_hint: 1, 0.2

    BoxLayout:
        size_hint: 1, 0.1
        orientation: 'horizontal'
        Button:
            text: 'Refresh'
        Button:
            text: 'Other Function'

    Data:

