<Interface>:
Interface:
    Button:
        text: "Green"
        pos: 100, 300
        size: 100, 100
        background_normal: ''
        background_color: 0, 1, 0, 1
    Button:
        text: "Red"
        pos: 200, 300
        size: 100, 100
        background_normal: ''
        background_color: 1, 0, 0, 1
    Button:
        text: "Blue"
        pos: 300, 300
        size: 100, 100
        background_normal: ''
        background_color: 0, 0, 1, 1
